# Generated by Django 3.0.6 on 2020-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('founded_at', models.DateTimeField(blank=True, null=True)),
                ('founder', models.CharField(max_length=200)),
                ('history', models.TextField()),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
