# Generated by Django 3.0.7 on 2020-06-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_trophies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophies',
            old_name='emblem',
            new_name='image',
        ),
    ]
