# Generated by Django 3.0.7 on 2020-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20200623_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophies',
            name='won_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
