# Generated by Django 3.0.7 on 2020-07-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20200623_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPosts',
        ),
    ]
