# Generated by Django 3.0.6 on 2020-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.TextField(default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
